<a href="https://colab.research.google.com/github/priyansupattanaik/CDAC/blob/main/2.%20Python/20March2026%20-%20Numpy%20%26%20Panda/20Mar2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Panda Library
================

In [ ]:
import numpy as np
import pandas as pd

Purpose :

1. Data Analysis
2. Data Manipulation
3. Data Cleaning
4. Prepare Structured Data

1. Series: 1D
2. DataFrame: 2D data

In [ ]:
#Creating Series:
s = pd.Series([10, 20, 30, 40 ,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
s = pd.Series([100, 200, 300], index=['a', 'b', 'c'])
s

a    100
b    200
c    300
dtype: int64

In [ ]:
s['a'] #access by label

np.int64(100)

In [ ]:
#Create Dataframe
data = {
  "Name" : ["Amit", "Neha", "Raj"],
  "Marks" : [85, 92, 78]
}
df = pd.DataFrame(data)
df

   Name  Marks
0  Amit     85
1  Neha     92
2   Raj     78

In [ ]:
data = [["Amit", 85], ["Neha", 92], ["Raj", 78]]
df = pd.DataFrame(data, columns=['Name', 'Marks'])
df

   Name  Marks
0  Amit     85
1  Neha     92
2   Raj     78

In [ ]:
data = [["P", 23, "Mumbai"], ["K", 25, "Bhubaneswar"], ["L", 30, "Pune"]]
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
df

In [17]:
df = pd.read_csv("/content/data.csv")
df

   ID    Name  Age  Marks     Dept  Salary        Date
0   1   Aarav   20     85       IT   50000  2026-01-15
1   2  Bhavna   21     90       IT   60000  2026-01-16
2   3  Charan   22     78       HR   40000  2026-01-17
3   4   Divya   20     92  Finance   65000  2026-01-18
4   5    Esha   23     67       HR   45000  2026-01-19
5   6  Farhan   21     88    Sales   55000  2026-01-20
6   7   Gauri   22     74  Finance   52000  2026-01-21
7   8   Harsh   20     81    Sales   48000  2026-01-22

In [22]:
df.head()

   ID    Name  Age  Marks     Dept  Salary        Date
0   1   Aarav   20     85       IT   50000  2026-01-15
1   2  Bhavna   21     90       IT   60000  2026-01-16
2   3  Charan   22     78       HR   40000  2026-01-17
3   4   Divya   20     92  Finance   65000  2026-01-18
4   5    Esha   23     67       HR   45000  2026-01-19

In [23]:
df.tail()

   ID    Name  Age  Marks     Dept  Salary        Date
3   4   Divya   20     92  Finance   65000  2026-01-18
4   5    Esha   23     67       HR   45000  2026-01-19
5   6  Farhan   21     88    Sales   55000  2026-01-20
6   7   Gauri   22     74  Finance   52000  2026-01-21
7   8   Harsh   20     81    Sales   48000  2026-01-22

In [21]:
df = pd.read_excel("/content/data xlsx")
df

   ID    Name  Age  Marks     Dept  Salary        Date
0   1   Aarav   20     85       IT   50000  2026-01-15
1   2  Bhavna   21     90       IT   60000  2026-01-16
2   3  Charan   22     78       HR   40000  2026-01-17
3   4   Divya   20     92  Finance   65000  2026-01-18
4   5    Esha   23     67       HR   45000  2026-01-19
5   6  Farhan   21     88    Sales   55000  2026-01-20
6   7   Gauri   22     74  Finance   52000  2026-01-21
7   8   Harsh   20     81    Sales   48000  2026-01-22

Data Exploring:

* head() : First 5 rows
* tail() : Last 5 rows
* info() : Data info
* describe() : Statistics
* shape() : Rows & Columns
* columns() : Columns Display the Columns Titles