Panda Library
================

In [99]:
import numpy as np
import pandas as pd

Purpose :

1. Data Analysis
2. Data Manipulation
3. Data Cleaning
4. Prepare Structured Data

1. Series: 1D
2. DataFrame: 2D data

In [100]:
#Creating Series:
s = pd.Series([10, 20, 30, 40 ,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [101]:
s = pd.Series([100, 200, 300], index=['a', 'b', 'c'])
s

a    100
b    200
c    300
dtype: int64

In [102]:
s['a'] #access by label

np.int64(100)

In [103]:
#Create Dataframe
data = {
  "Name" : ["Amit", "Neha", "Raj"],
  "Marks" : [85, 92, 78]
}
df = pd.DataFrame(data)
df

   Name  Marks
0  Amit     85
1  Neha     92
2   Raj     78

In [104]:
data = [["Amit", 85], ["Neha", 92], ["Raj", 78]]
df = pd.DataFrame(data, columns=['Name', 'Marks'])
df

   Name  Marks
0  Amit     85
1  Neha     92
2   Raj     78

In [105]:
data = [["P", 23, "Mumbai"], ["K", 25, "Bhubaneswar"], ["L", 30, "Pune"]]
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
df

  Name  Age         City
0    P   23       Mumbai
1    K   25  Bhubaneswar
2    L   30         Pune

In [106]:
df = pd.read_csv("/content/data.csv")
df

   ID    Name  Age  Marks     Dept  Salary        Date
0   1   Aarav   20     85       IT   50000  2026-01-15
1   2  Bhavna   21     90       IT   60000  2026-01-16
2   3  Charan   22     78       HR   40000  2026-01-17
3   4   Divya   20     92  Finance   65000  2026-01-18
4   5    Esha   23     67       HR   45000  2026-01-19
5   6  Farhan   21     88    Sales   55000  2026-01-20
6   7   Gauri   22     74  Finance   52000  2026-01-21
7   8   Harsh   20     81    Sales   48000  2026-01-22

In [107]:
df.head()

   ID    Name  Age  Marks     Dept  Salary        Date
0   1   Aarav   20     85       IT   50000  2026-01-15
1   2  Bhavna   21     90       IT   60000  2026-01-16
2   3  Charan   22     78       HR   40000  2026-01-17
3   4   Divya   20     92  Finance   65000  2026-01-18
4   5    Esha   23     67       HR   45000  2026-01-19

In [108]:
df.tail()

   ID    Name  Age  Marks     Dept  Salary        Date
3   4   Divya   20     92  Finance   65000  2026-01-18
4   5    Esha   23     67       HR   45000  2026-01-19
5   6  Farhan   21     88    Sales   55000  2026-01-20
6   7   Gauri   22     74  Finance   52000  2026-01-21
7   8   Harsh   20     81    Sales   48000  2026-01-22

In [109]:
df = pd.read_excel("/content/data.xlsx")
df

   ID    Name  Age  Marks     Dept  Salary        Date
0   1   Aarav   20     85       IT   50000  2026-01-15
1   2  Bhavna   21     90       IT   60000  2026-01-16
2   3  Charan   22     78       HR   40000  2026-01-17
3   4   Divya   20     92  Finance   65000  2026-01-18
4   5    Esha   23     67       HR   45000  2026-01-19
5   6  Farhan   21     88    Sales   55000  2026-01-20
6   7   Gauri   22     74  Finance   52000  2026-01-21
7   8   Harsh   20     81    Sales   48000  2026-01-22

Data Exploring:

* head() : First 5 rows
* tail() : Last 5 rows
* info() : Data info
* describe() : Statistics
* shape() : Rows & Columns
* columns() : Columns Display the Columns Titles

In [110]:
print(df.head())

   ID    Name  Age  Marks     Dept  Salary        Date
0   1   Aarav   20     85       IT   50000  2026-01-15
1   2  Bhavna   21     90       IT   60000  2026-01-16
2   3  Charan   22     78       HR   40000  2026-01-17
3   4   Divya   20     92  Finance   65000  2026-01-18
4   5    Esha   23     67       HR   45000  2026-01-19

In [111]:
print(df.tail())

   ID    Name  Age  Marks     Dept  Salary        Date
3   4   Divya   20     92  Finance   65000  2026-01-18
4   5    Esha   23     67       HR   45000  2026-01-19
5   6  Farhan   21     88    Sales   55000  2026-01-20
6   7   Gauri   22     74  Finance   52000  2026-01-21
7   8   Harsh   20     81    Sales   48000  2026-01-22

In [112]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    8 non-null      object
 2   Age     8 non-null      int64
 3   Marks   8 non-null      int64
 4   Dept    8 non-null      object
 5   Salary  8 non-null      int64
 6   Date    8 non-null      object
dtypes: int64(4), object(3)
memory usage: 580.0+ bytes
None

In [113]:
print(df.describe())

            ID        Age      Marks        Salary
count  8.00000   8.000000   8.000000      8.000000
mean   4.50000  21.125000  81.875000  51875.000000
std    2.44949   1.125992   8.576338   8061.150219
min    1.00000  20.000000  67.000000  40000.000000
25%    2.75000  20.000000  77.000000  47250.000000
50%    4.50000  21.000000  83.000000  51000.000000
75%    6.25000  22.000000  88.500000  56250.000000
max    8.00000  23.000000  92.000000  65000.000000

In [114]:
print(df.shape)

(8, 7)

In [115]:
print(df.columns)

Index(['ID', 'Name', 'Age', 'Marks', 'Dept', 'Salary', 'Date'], dtype='object')

In [116]:
#Column Section
df[["Name"]]

     Name
0   Aarav
1  Bhavna
2  Charan
3   Divya
4    Esha
5  Farhan
6   Gauri
7   Harsh

In [117]:
#Column Selection
df[["Name","Salary"]]

     Name  Salary
0   Aarav   50000
1  Bhavna   60000
2  Charan   40000
3   Divya   65000
4    Esha   45000
5  Farhan   55000
6   Gauri   52000
7   Harsh   48000

In [118]:
#Row Selection
df.loc[5] #Label based access

ID                 6
Name          Farhan
Age               21
Marks             88
Dept           Sales
Salary         55000
Date      2026-01-20
Name: 5, dtype: object

In [119]:
#Row Selection
df.iloc[0] #index-based access

ID                 1
Name           Aarav
Age               20
Marks             85
Dept              IT
Salary         50000
Date      2026-01-15
Name: 0, dtype: object

In [120]:
#Filtering Data
df[df['Salary'] > 55000]

   ID    Name  Age  Marks     Dept  Salary        Date
1   2  Bhavna   21     90       IT   60000  2026-01-16
3   4   Divya   20     92  Finance   65000  2026-01-18

In [121]:
df[(df['Salary'] > 55000) & (df['Age'] < 90)]

   ID    Name  Age  Marks     Dept  Salary        Date
1   2  Bhavna   21     90       IT   60000  2026-01-16
3   4   Divya   20     92  Finance   65000  2026-01-18

In [122]:
df["Dept"] = ["HR", "EDU", "HR", "EDU", "HR", "EDU", "HR", "EDU"]
df

   ID    Name  Age  Marks Dept  Salary        Date
0   1   Aarav   20     85   HR   50000  2026-01-15
1   2  Bhavna   21     90  EDU   60000  2026-01-16
2   3  Charan   22     78   HR   40000  2026-01-17
3   4   Divya   20     92  EDU   65000  2026-01-18
4   5    Esha   23     67   HR   45000  2026-01-19
5   6  Farhan   21     88  EDU   55000  2026-01-20
6   7   Gauri   22     74   HR   52000  2026-01-21
7   8   Harsh   20     81  EDU   48000  2026-01-22

In [123]:
#Adding and Modifying data
df["section"] = ["HR", "EDU", "HR", "EDU", "HR", "EDU", "HR", "EDU"]
df

   ID    Name  Age  Marks Dept  Salary        Date section
0   1   Aarav   20     85   HR   50000  2026-01-15      HR
1   2  Bhavna   21     90  EDU   60000  2026-01-16     EDU
2   3  Charan   22     78   HR   40000  2026-01-17      HR
3   4   Divya   20     92  EDU   65000  2026-01-18     EDU
4   5    Esha   23     67   HR   45000  2026-01-19      HR
5   6  Farhan   21     88  EDU   55000  2026-01-20     EDU
6   7   Gauri   22     74   HR   52000  2026-01-21      HR
7   8   Harsh   20     81  EDU   48000  2026-01-22     EDU

In [124]:
#Modify Data
df["Salary"] = df["Salary"] + 1000
df

   ID    Name  Age  Marks Dept  Salary        Date section
0   1   Aarav   20     85   HR   51000  2026-01-15      HR
1   2  Bhavna   21     90  EDU   61000  2026-01-16     EDU
2   3  Charan   22     78   HR   41000  2026-01-17      HR
3   4   Divya   20     92  EDU   66000  2026-01-18     EDU
4   5    Esha   23     67   HR   46000  2026-01-19      HR
5   6  Farhan   21     88  EDU   56000  2026-01-20     EDU
6   7   Gauri   22     74   HR   53000  2026-01-21      HR
7   8   Harsh   20     81  EDU   49000  2026-01-22     EDU

In [125]:
#Delete Data
df = df.drop("section", axis = 1, inplace=True)
df

In [126]:
#Handling Missing Data
df.isnull()

AttributeError: 'NoneType' object has no attribute 'isnull'