Panda Library
================

In [1]:
import numpy as np
import pandas as pd

Purpose :

1. Data Analysis
2. Data Manipulation
3. Data Cleaning
4. Prepare Structured Data

1. Series: 1D
2. DataFrame: 2D data

In [2]:
#Creating Series:
s = pd.Series([10, 20, 30, 40 ,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
s = pd.Series([100, 200, 300], index=['a', 'b', 'c'])
s

a    100
b    200
c    300
dtype: int64

In [7]:
s['a'] #access by label

np.int64(100)

In [11]:
#Create Dataframe
data = {
  "Name" : ["Amit", "Neha", "Raj"],
  "Marks" : [85, 92, 78]
}
df = pd.DataFrame(data)
df

   Name  Marks
0  Amit     85
1  Neha     92
2   Raj     78

In [13]:
data = [["Amit", 85], ["Neha", 92], ["Raj", 78]]
df = pd.DataFrame(data, columns=['Name', 'Marks'])
df

   Name  Marks
0  Amit     85
1  Neha     92
2   Raj     78

In [ ]:
data = [["P", 23, "Mumbai"], ["K", 25, "Bhubaneswar"], ["L", 30, "Pune"]]
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
df